site_name: Inteligência Artificial e Robótica 
#repo_url: https://github.com/Insper/ia_bcc/
#repo_name: Inteligência Artificial e Robótica
#site_url: https://insper.github.io/ia_bcc/

theme:
    name: 'material'

extra_css:
  - css/custom.css

nav:
  - 'Home': 'index.md'
  - 'Ementa': 'ementa.md'
  - 'Plano de Aula': 'plano_de_aulas.md'
  - 'Critérios para Aprovação': 'avaliacao.md'
  - 'Aulas':
    - 'Introdução':
      - 'aulas/01_introducao_ia/index.md'
      - 'aulas/02_agentes_autonomos/index.md'
      - 'aulas/03_configuracao/index.md'
    - 'Busca em espaço de estados':
      - 'aulas/04_modelagem/index.md'
#      - 'aulas/04_modelagem_espaco/index.md'
      - 'aulas/04_x_buscas/index.md'
#      - 'aulas/04_x_modelagem/index.md'
      - 'aulas/05_busca_com_custo/index.md'
##    # - 'aulas/05_x_busca_cega/index.md'
      - 'aulas/07_revisao/index.md'
    - 'Busca com heurística':
      - 'aulas/08_heuristica/index.md'
      - 'aulas/08_heuristica_parte_2/index.md'
      - 'aulas/08_heuristica_parte_3/index.md'
      - 'aulas/08_heuristica_parte_3_aps/index.md'
##    # - 'aulas/10_heuristica_revisao/index.md'
##      - 'aulas/11_contribuindo_aigyminsper/index.md'
#
    - 'Programação por restrições':
      - 'aulas/12_csp/index.md'
#
    - 'Ambientes competitivos':
      - 'aulas/13_jogos/index.md'
#      - 'aulas/14_tictactoe/tictactoe.ipynb'
#      - 'aulas/14_tictactoe/index.md'
#
###    - 'aulas/14_competicao/index.md'
    - 'Aprendizagem por reforço':
      - 'aulas/15_rl/index.md'
      - 'aulas/15_rl_parte2/index.md'
      - 'aulas/15_rl_sarsa/index.md'
      - 'aulas/15_xnon_determ/index.md'
#
##  - 'Avaliações atuais':
##    - 'avaliacoes/2024_1_intermediaria/index.md'
##    - 'avaliacoes/2024_1_final/index.md'
##    - 'avaliacoes/2024_1_gabarito/index.md'
##    - 'avaliacoes/2023_2_sub/index.md'
  - 'Projetos atuais':
    - 'projetos/2025_01_intermediario/index.md'
##    - 'projetos/15_rl/index.md'
#    - 'projetos/2024_02_robo/index.md'
#
#
###   - 'Tópicos sobre IA':
###    - 'aulas/99_topicos/index.md'
  - 'Referências':
    - 'referencias/01_introducao/index.md'
    - 'referencias/03_algoritmos_busca/index.md'
    - 'referencias/03_csp/index.md'
###    - 'referencias/03_dijkstra/index.md'
    - 'referencias/04_busca_competitiva/index.md'
    - 'referencias/05_jogos/index.md'
#    - 'referencias/06_rl/index.md'
  - 'Exercícios e avaliações antigas':
    - 'exercicios/index.md'
#  
#  - 'Comentários': 'comentarios.md'


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - js/markdown-enhancer.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: "docs/_snippets"
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes

plugins: 
  - git-revision-date-localized
  - mkdocs-jupyter



